# Kubernetes Operator Cluster Service Version 

apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: nuodb-ce-operator.v0.0.1
spec:
  version: 0.0.1
  displayName: nuodb
  provider:
    name: NuoDB Inc.
    url: nuodb.com
  maturity: alpha
  version: 0.0.1
  maintainers:
    - email: tgates@nuodb.com
      name: NuoDB Inc.
  labels:
    olm-owner-enterprise-app: nuodb-ce-operator
    olm-status-descriptors: nuodb-ce-operator.v0.0.1
  description: NuoDB database system
  icon:
  - mediatype: image/jpeg
    base64data: /9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxAQBhUSEREVExEWERMQEhMWGQ8XFhgVGBYXFhUSExcaHiggGBomGxUVIjIhJSkuLi4uGB8zODUtNygtLisBCgoKDg0OFxAQGy0fIB8rLTErNysrNy0rLi0tNy0vLTAuLTEuLTctOC03Kys3LSstLS0vLy0tLS0tLS0uLSstLf/AABEIAMgAyAMBEQACEQEDEQH/xAAbAAEAAwEBAQEAAAAAAAAAAAAABAUGAgMBB//EADgQAAIBAQUECAUDAwUAAAAAAAABAgMEBREhMQYSUYFBYXGRobHB0RMiMkJyUsLhNEOSFiMkYoL/xAAaAQEAAgMBAAAAAAAAAAAAAAAAAgMBBQYE/8QAMREBAAIBAwIEBAYBBQEAAAAAAAECAwQFERIxEyFBcTJRgaEiM0JhkdGxI1JTweEV/9oADAMBAAIRAxEAPwD9xAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHNSoowbeSSxb6uJG1orEzPaAhJOOKeKeaa0M1tFo5jzHRkAAAAAAAAAAAAAAAAAAAAAAAAABzOKcWno1gyNqxaJifUY+hbKtmtMop4pSacXo8Hr1HH01WbR5bUifKJ7T2W8RLR3fetOssF8s/wBL9H0nR6TccWojiPKflKua8J572AAAAAAAAAAAq72vb4FRRUd5tYvPDBdHRn09xrNfuMaaYrEczKUV5Q7PtFjXSnBRi3g3i3h1nixb31XiL14iWehfp5G/ieUH0yAAAAAAAAAABlNpaG7b97olHHmsn4Yd5ym84enPF/8AdH3hZWfJUp5moiZieYSXN3X9KGEavzR/V9y7eJutHu96cVy+cfP1/wDUZq0dntEKlPehJNdXk+B0eLNTLXqpPMK+HqWgAAAAAAABiLztPxbdKXRjhHsWS9+ZxGuz+Nntb+PaFsRxCKeRlotnbyxXwpvNfQ+r9J0e0a7mPBv9P6QtHqvzfoAAAAAAAAAABU7S0N6wb3TCSfJ5P07jU7zh68HVH6Z+yVJ82UOTWAHrZrTOnU3oSafn1NdJdh1GTDbqpPBMctJd1+wn8tTCEuP2v25nSaPdseX8OT8M/ZXNVwbeJRDIAAAACDfVp+Hd8n0v5I9r/jF8jw7jn8HT2n1nyj6s1jmWMOLWr+5buhVu176zc3hJarJaeJ0G26HHn009cd58p9UbTxKBb7sqUJ7yzinipro4Y8DwanQZtLbqjziPWGYtEtFc94KtZ8/rWUl6rqZ0W36yNRj5n4o7q5jhPPewAAAAAB8ksUYmOY4GUtNvtNG1OHxG8HliovFdDzXA5TPrNXpss0m3b5/JZERLqntDWWqg+TT8yVN6zx3iJOiHtPaBToOE6WTi4tqXHqwLbbzGSk0vTvHpJ0qI0SQAAAWF33vUo5fVD9L6PxfQbHSbllweXxV+UsTWJXNDaGi/qUo8sV4Z+BusW84LfFzVCaytqVRSpqUXimsUza0vF6xavnEouiQAAMztPacbRGmtIrF9r/jzOZ3vP1Xrjj08/rKykeqkNGk2NwwwuqHXi+9v0wOy2unTpafurt3T2sUe+Y5RVlS69y0fEofLLph9sl0pcPLQ1l9B4eTxsHlPrHpP9JdXzWUJYwxwa6nr2GyrPMcouiQAAAAABSbS2PeoKotY5S/H+H5s0m86XrxxljvXv7J1n0Zk5hMAAAAAAAAtbkvT4VTcm/8Abb/xfHsNttmv8G3h3+GfsjavLVp5HVxPKt9MjmpNRg29Em32Ija0VibT6DC2ms6lolN6ybfsjhM+WcuS159ZXQ8iobmwQ3bFBcIRXhmd3pa9OGlflEKpSC9gAAAAAAAAAczinFp5prBrqMWrFomJ9RibwsrpWtwemsXxT0Zw+s084Mtqfx7LonmEY8wAAAAAAAAX+z96YNUpvLSD/a/Q6Datw44w5J9p/wCkLVaI6JBVbR2ncsG6tZvd5av25mq3fP4eDpjvby/tKsebJnJLHVOG9US4tLvJY69V4r85G+SyO/iOIUvpkAAAAAAAAAACn2jse/Zd9fVDXrj092veafd9L4mLxK96/wCEqyyxyqwAAAAAAAAAai4r0+JH4c386WT/AFL3Op2vcPFjw7/FH3V2jhV7Q2nfvDBaQW7z1ftyNVu+fxM/THavl/aVY8lWatJKuuG9eNNf90+7P0PVoa9Woxx+7E9m3O4VAAAAAAAAAAAA+SWKwehiYiY4kYm87J8G2OPRrH8Xp7cjiddp5wZpr6enstieYRTyMgAAAAAAAH2EmpJp4NPFMzW01mLR5TATk3Nt5tttvreotabTMz3kfDAs9nYY3onwjJ+GHqbPaKdWpiflEo27NcderAAAAAAAAAAAAAqdobHv2PeS+aGL/wDPSvXkandtL4uLqjvX/HqlWfNlDk1gAAAAAAAAAAALvZWH/JnLhFLveP7TebHX/Uvb9kbtMdMrAAAAAAAAAAAAAMxMcjG3tYHRtLwT3G8Yvo/HkcbuGjtgyTMR+Gey2s8oB4GQAAAAAAAAB3RoynLCMXJ9SbLMeHJknilZk5afZ6xTpUpOawcmsstFjw7Tp9p0t8FLeJHEyrtPK3NuiAAAAAAAAAAAAAA5qQUoYSSaeqeaI2pW8cWjmBn7yuDD5qPOD/a/RnP6zZ+Ob4P4/pOLfNQyi1LBrBrJp68zQWrNZ4nylN8MAAAASLJYqlV/JHHDV5JLmz0YNJlz/lxyTMQtbPs5J/XNLqjn4s22HY7T55LceyPWs7PctCH27z4yz8NPA2eLa9Nj/Tz7ozaU+EUo4JYLgj31rFY4iOEXRIAAAAAAAAAAAAAAAAACFeF2U60c1hLoktefFHi1WhxaiPxeU/NmJ4ZS32KVGtuyafBprxWqOU1Wltp79MzE+y2J5RjygAA0uyv9PP8AJeR02x/l390Lrw3iAAAAAAAAAAAAAAAAAAfG8EYmeBCtF70IazTfCOflkeLLuOnxd7cz+3mzFZVdp2kf9uHOXsvc1ebfP+Ov8pRRWWi8609ZvDgsl4a8zV5tw1GXvb+PJLphDPHyyAAAGl2V/p5/kvI6bY/y7+6F14bxAAAAAAAAAAAAAABxVqxhHGUlFcW0iF8laRzaePcVtov6jHTGb6ll3v0Nbl3fT07T1eyUVlV2jaGq/oioL/J+3gavLvWW3wRFfulFYVte1VKj+ebl1N5d2hrMupy5fjtMpcQ8SkdwpSl9MW+xNk64r27VmfoPeF3VnpSlzTXmeiuh1Fu1JY5hIhcdof2pdrj6MvrtGqn04+p1Q94bOVemUF/k/Q9FdkzT3tEMdaRDZrjV7o/yeiuxR+q/2Y60iGztFaym+ccPIvrsmCO8zLHXKwsVihRg1BYYvF5tmx0+lx6eJrjjuxM8pB6GAAAAAAAAAAA5qTSWePJN+CI2t0xyIlW11P7dGUuuTjFeLx8Dy31GXtjxzPv5M8Qh1adtqfdCmuCbx78GeK9Nwy+sVj9mfwo3+nqkpYzq58cHJ97aPN/8bJeecmTn7s9T2hs3DpqSfZur3Lq7HijvaTre8LgoLVSfa36YHors+mjvEz9WOqUiF1UFpTjzxfmX12/TV7UhjmXvTs1OP0wiuxJHorgx17ViPoxy9i0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/2Q==
  install:
    strategy: deployment
    spec:
      permissions:
      - serviceAccountName: nuodb-ce-operator
        rules:
        - apiGroups:
          - nuodb.com
          resources:
          - "*"
          verbs:
          - "*"
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          - namespaces
          verbs:
          - "*"
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - "*"
      deployments:
      - name: nuodb-ce-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: nuodb-ce-operator
          template:
            metadata:
              labels:
                app: nuodb-ce-operator
            spec:
              containers:
                - name: nuodb-ce-operator-olm-owned
                  image: docker.io/nuodb/nuodb-ce-operator:v0.0.1
                  imagePullPolicy: Always
                  env:
                  - name: MY_POD_NAMESPACE
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace
                  - name: WATCH_NAMESPACE
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace
                  - name: MY_POD_NAME
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.name
              restartPolicy: Always
              terminationGracePeriodSeconds: 5
              serviceAccountName: nuodb-ce-operator
              serviceAccount: nuodb-ce-operator
  customresourcedefinitions:
    owned:
      - description: Represents a Nuodb instance
        displayName: Nuodb Server
        kind: Nuodb
        name: nuodb-ce.nuodb.com
        version: v1alpha1
        resources:
          - kind: Deployment
            version: v1beta2
          - kind: ReplicaSet
            version: v1beta2
          - kind: Pod
            version: v1
          - kind: Service
            version: v1
        specDescriptors:
          - description: The desired number of member Pods for the deployment.
            displayName: Size
            path: replicaCount
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:podCount'
        statusDescriptors:
          - description: The current status of the application.
            displayName: Status
            path: phase
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes.phase'
          - description: Explanation for the current status of the application.
            displayName: Status Details
            path: reason
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes.phase:reason'
